# Confidence interval

The real life problem.May be I should call it Kuddus shaheber porishonkhan dorshon?

Suppose world bank wants to do a study, after the Bangladesh turned into middle income country, what happened to the income of Dhaka city. so we want to know the average income, how to find it? 

By a sample, what will be the sample size, that we will discuss little bit later but say we found it to be 5000. Suppose I have survey firm, I got high connections and got the deal. I thought hey I live in Zigatala, how about go around and ask 5000 people in zigatala, what is wrong in that? 

It will not be representative, it will be a biased sample. What does it mean to be biased?  it does not tend to truth. It can be greater than the true value, postiviely biased. It can be less than the true value, negatively biased. Then what will be the right way to pick the sample? 

Random sampling, what does it mean to be random sampling, equal probability of every one coming up in the population area. Then it will be representative. Now let's say we found the average income of 5000 sample is monthly 18000 taka. What we do with that number? 

We run to the mission head of WB and say hey we are done, here is monthly 18000 taka. How come we can rely on just 5000 fromm 2 crore people? Being smart, he asks how about if we took another 5000, will we end up with still 18000? If you can't answer these questions, your bill is suspended and you go home. 

Then you open up your statistics book and come up with a concept called sampling distribution.Distribution of sample statistics.There can be many samples and from each of it we can find the average.The probability distribution of sample average is called sampling distribution. 

What is probability? The science of dealing with uncertainty.Example please: 
* Insurance
* Credit loan
* Flight booking 

How is  the probability  relevant in the case of Mr kuddus sampling above in WB study? 

It is relevant, because in true we are dealing with a theoretical world which consistst of population but in real world, we are dealing with sample. from real world, we are trying to have an idea about theoretical world.
but in real world, we have considerable bit of uncertainty becaue of limited amount of error. we are not 100 percent sure that we will be able 
to estimate the true value of the parameter. do deal with this uncertainty we will have to deal with probability theory.But what about probability distribution? 

What is that? how do you distribute probability? 

For examaple I have 10 envelops with 1 to 10 numbers above indicating number of thousand taka note inside. Then, i want to distribute the money, how do i distribute? I know zahed, give him 10, nahin faryana our students give them another 4 3. But if i want to be impartial what I want to be doing? 

So each of the 10 comes should have equal chance. It will be done by lottery How will the prob dist look like? a flat curve.It's a probability distribution Now go back to text book probability distribution 

coin toss 

dice roll 

At this point, I will just go to the need for probability html file 

start with slide number 15, coin flips 

flipped coin 10 times, did not 6 H out of 10 
but theorteical world says it will be 5 of 10 

how to reconcile 

Now comes the bottle cap, red side, silver side 
after 10 flips we found 4 out 10, 

what will happen in the theoretical world? 

now go to some probability basics 

Experiment: flip two coins 

calculate probability 

probability of sample space 

Random variable, what is that 

what is variable, something which value varies 

why random variable? 

the value of the variable is randomly assigned 

Y = no. of heads in two coin toss experiment 

sample space 
probability of sample space 

some probability calculation scenario 

meaning of probability 
theoretical
long run 
subjective 

Second example: 

bottle cap 
here the probability is not even 
so important 
so how to calculate joint probability 

